CREATE DATABASE checkout;

USE checkout;

CREATE TABLE users (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  addressLine1 TEXT NOT NULL,
  addressLine2 TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zip INTEGER(5) NOT NULL,
  phone TEXT NOT NULL,
  creditCard INTEGER NOT NULL,
  expiryDate TEXT NOT NULL,
  CVV INTEGER(3) NOT NULL,
  billingZip INTEGER(5) NOT NULL
);